services:
  search:
    image: apohllo/elasticsearch-morfologik:8.15.2
    ports:
      - "9200:9200"
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
    command: >
      sh -c "
      if [ -d /usr/share/elasticsearch/plugins/analysis-morfologik ]; then
        bin/elasticsearch-plugin remove analysis-morfologik;
      fi &&
      bin/elasticsearch-plugin install --batch pl.allegro.tech.elasticsearch.plugin:elasticsearch-analysis-morfologik:8.15.2 &&
      bin/elasticsearch
      "

  kibana:
    image: kibana:8.15.2
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://search:9200"

